// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbQdxxL6jx_WTr_GtHg4BdhyDOvb2R1cY',
    appId: '1:662536524693:web:33a4cabdc4434b65d29c9c',
    messagingSenderId: '662536524693',
    projectId: 'eriell-d1f23',
    authDomain: 'eriell-d1f23.firebaseapp.com',
    storageBucket: 'eriell-d1f23.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbVvWpnH4Q_nxScYslS-Z0aNf6mkH87Y4',
    appId: '1:662536524693:android:d24624ffe804135fd29c9c',
    messagingSenderId: '662536524693',
    projectId: 'eriell-d1f23',
    storageBucket: 'eriell-d1f23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtt7j8g6mFw8NVYI0DTpkdaJJRAO3nPh4',
    appId: '1:662536524693:ios:dc06ab5c04b0fffed29c9c',
    messagingSenderId: '662536524693',
    projectId: 'eriell-d1f23',
    storageBucket: 'eriell-d1f23.appspot.com',
    iosBundleId: 'com.example.eriellTest',
  );
}
